config:
  processor: "../functions.js"
  environments:
    localhost:
      target: http://localhost:3000
    staging:
      target: https://pix-api-integration-pr561.scalingo.io
  variables:
    # Thinking time is in seconds
    needRandomThinkingTime: true
    minThinkingTime: 5
    maxThinkingTime: 30
